apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
spec:
  project: capstone-platform
  source:
    repoURL: https://github.com/kwdowicz/kub-capstone.git
    targetRevision: main
    path: gitops/workloads/echo
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/audit-version: latest
        pod-security.kubernetes.io/warn: restricted
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
